# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# HABILITA O USO DE FRAMEWORKS PARA TODO O PROJETO.
# Isto é necessário para que a extensão e o app principal sejam compatíveis.
use_frameworks!

target 'RaspaPremiada' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

# esse trecho vou adicionado apos adicionar o target OnesignalNotificationServiceExtension
# (Notification Service Extension)
target 'OneSignalNotificationServiceExtension' do
  # A linha 'use_frameworks!' aqui abaixo é agora redundante, pois já foi
  # declarada globalmente. Pode ser removida ou mantida, não fará diferença.
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
end